version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:6.0.4-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass root
    sysctls:
      net.core.somaxconn: '511'
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    volumes:
      - ./tables/:/docker-entrypoint-initdb.d
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    # command: kafka scale=3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
