version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    volumes:
      - ./noazet-server/tables/:/docker-entrypoint-initdb.d
      - ./store/:/var/lib/mysql/
